# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 http://thitgaluoc.com/

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             

title:               Thịt Gà Luộc

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Không ăn cầm lấy cho nhau bằng lòng🎵

# The tags listed as entries in the sidebar
sidebar_tags:        []

# Fallback image and color if not overwritten for tag or post
image:               /public/img/luoc.jpg
color:               '#A85641'

# Fonts
font:                '"Noto Sans", Georgia, serif'
font_accent:         '"Roboto Slab", "Noto Sans", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|Noto+Sans:400,400italic,700,700italic'

# About yourself
author:
  name:              'Tuấn Trần'

  # This photo will be used in the about section
  photo:             https://graph.facebook.com/1091384545/picture?type=normal
  photo2x:           https://graph.facebook.com/1091384545/picture?type=large

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    Mình là Tuấn.
    Hiện tại mình chưa có gì để viết cả, anh em quay lại sau nhé :v

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    #facebook:        7thgearbox
    #twitter:         _username_
    #google:          _number_
    #vk:              _username_
    #youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    # github:          _username_
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
#google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
